// <auto-generated />
namespace IVH7_Cinema.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lostobject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lostobject));
        
        string IMigrationMetadata.Id
        {
            get { return "201504021446281_lostobject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
