//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVH7_Cinema.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IVH7_Cinema.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres:.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul een geldig adres in.
        /// </summary>
        public static string AdressInvalid {
            get {
                return ResourceManager.GetString("AdressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummer:.
        /// </summary>
        public static string AdressNumber {
            get {
                return ResourceManager.GetString("AdressNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul een adres is.
        /// </summary>
        public static string AdressRequired {
            get {
                return ResourceManager.GetString("AdressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volgende.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betalen.
        /// </summary>
        public static string ButtonPay {
            get {
                return ResourceManager.GetString("ButtonPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woonplaats:.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul een geldige woonplaats in.
        /// </summary>
        public static string CityInvalid {
            get {
                return ResourceManager.GetString("CityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul een plaats in.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U kunt uw bestelling ophalen met de volgende code: .
        /// </summary>
        public static string CodeSuccess {
            get {
                return ResourceManager.GetString("CodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binnenkort verwacht.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw Email:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U heeft zich al aangemeld voor de nieuwsbrief.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is niet geldig.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het email adres kon niet gevonden worden.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het email adres is verwijderd.
        /// </summary>
        public static string EmailRemoved {
            get {
                return ResourceManager.GetString("EmailRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul uw email in.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U hebt zich succesvol aangemeld voor de nieuwsbrief van CinemA.
        /// </summary>
        public static string EmailSubscribed {
            get {
                return ResourceManager.GetString("EmailSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populaire films.
        /// </summary>
        public static string HomePopular {
            get {
                return ResourceManager.GetString("HomePopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koop hier je tickets!.
        /// </summary>
        public static string HomeTickets {
            get {
                return ResourceManager.GetString("HomeTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom bij CinemA. Een onvergetelijke filmervaring..
        /// </summary>
        public static string HomeWelcome {
            get {
                return ResourceManager.GetString("HomeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze code kunt u invoeren bij de touchscreens bij de bioscoop..
        /// </summary>
        public static string InfoSucces1 {
            get {
                return ResourceManager.GetString("InfoSucces1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onthoud deze code goed of bewaar deze op de email die u nu zult ontvangen..
        /// </summary>
        public static string InfoSucces2 {
            get {
                return ResourceManager.GetString("InfoSucces2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U kunt uw kaarten ook uitprinten met het pdf bestand dat nu gedownload wordt..
        /// </summary>
        public static string InfoSucces3 {
            get {
                return ResourceManager.GetString("InfoSucces3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bioscopen.
        /// </summary>
        public static string MenuCinemas {
            get {
                return ResourceManager.GetString("MenuCinemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoofdpagina.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films.
        /// </summary>
        public static string MenuMovies {
            get {
                return ResourceManager.GetString("MenuMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwsbrief.
        /// </summary>
        public static string MenuNews {
            get {
                return ResourceManager.GetString("MenuNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze week te zien.
        /// </summary>
        public static string MenuNow {
            get {
                return ResourceManager.GetString("MenuNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijkwijzer.
        /// </summary>
        public static string MovieClassification {
            get {
                return ResourceManager.GetString("MovieClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL.
        /// </summary>
        public static string MovieDescription {
            get {
                return ResourceManager.GetString("MovieDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisseur.
        /// </summary>
        public static string MovieDirector {
            get {
                return ResourceManager.GetString("MovieDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duur.
        /// </summary>
        public static string MovieDuration {
            get {
                return ResourceManager.GetString("MovieDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string MovieGenre {
            get {
                return ResourceManager.GetString("MovieGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        public static string MovieLanguage {
            get {
                return ResourceManager.GetString("MovieLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht alle films.
        /// </summary>
        public static string MovieOverviewHeader {
            get {
                return ResourceManager.GetString("MovieOverviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDB Rating.
        /// </summary>
        public static string MovieRating {
            get {
                return ResourceManager.GetString("MovieRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatie.
        /// </summary>
        public static string MovieSpecs {
            get {
                return ResourceManager.GetString("MovieSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondertiteling.
        /// </summary>
        public static string MovieSubtitles {
            get {
                return ResourceManager.GetString("MovieSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets en tijden.
        /// </summary>
        public static string MovieTicketHeader {
            get {
                return ResourceManager.GetString("MovieTicketHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw naam:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam bevat te veel tekens.
        /// </summary>
        public static string NameLong {
            get {
                return ResourceManager.GetString("NameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul uw naam in.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwsbrief.
        /// </summary>
        public static string NewsletterHeader {
            get {
                return ResourceManager.GetString("NewsletterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voor de laatste nieuwtjes en acties kunt u zich aanmelden voor de nieuwsbrief. U ontvangt elke 2 weken de CinemA InfoLetter in uw mailbox..
        /// </summary>
        public static string NewsletterInfo {
            get {
                return ResourceManager.GetString("NewsletterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films deze week.
        /// </summary>
        public static string NowOverviewHeader {
            get {
                return ResourceManager.GetString("NowOverviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul een geldig nummer in.
        /// </summary>
        public static string NumberInvalid {
            get {
                return ResourceManager.GetString("NumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul een nummer in.
        /// </summary>
        public static string NumberRequired {
            get {
                return ResourceManager.GetString("NumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Keuze.
        /// </summary>
        public static string OrderChoice {
            get {
                return ResourceManager.GetString("OrderChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestel Tickets.
        /// </summary>
        public static string OrderHeader {
            get {
                return ResourceManager.GetString("OrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal aantal beschikbare stoelen:.
        /// </summary>
        public static string OrderSeats {
            get {
                return ResourceManager.GetString("OrderSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal kaartjes.
        /// </summary>
        public static string OrderTableAmount {
            get {
                return ResourceManager.GetString("OrderTableAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijs.
        /// </summary>
        public static string OrderTablePrice {
            get {
                return ResourceManager.GetString("OrderTablePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarief.
        /// </summary>
        public static string OrderTableTariff {
            get {
                return ResourceManager.GetString("OrderTableTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal.
        /// </summary>
        public static string OrderTableTotal {
            get {
                return ResourceManager.GetString("OrderTableTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De films voor vandaag.
        /// </summary>
        public static string OverviewToday {
            get {
                return ResourceManager.GetString("OverviewToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betaling.
        /// </summary>
        public static string PaymentHeader {
            get {
                return ResourceManager.GetString("PaymentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul een betaalwijze in.
        /// </summary>
        public static string PaymentRequired {
            get {
                return ResourceManager.GetString("PaymentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserveer nu.
        /// </summary>
        public static string PaymentReserve {
            get {
                return ResourceManager.GetString("PaymentReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw betaling is geslaagd!.
        /// </summary>
        public static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies betaalwijze:.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquete.
        /// </summary>
        public static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenseer een movie.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaal.
        /// </summary>
        public static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afmelden.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode:.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul een geldige postcode in.
        /// </summary>
        public static string ZipCodeInvalid {
            get {
                return ResourceManager.GetString("ZipCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul een postcode in.
        /// </summary>
        public static string ZipCodeRequired {
            get {
                return ResourceManager.GetString("ZipCodeRequired", resourceCulture);
            }
        }
    }
}
